"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-01 10:51:20.191850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('admin_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('host_or_celebrant_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_time', sa.String(length=100), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=False),
    sa.Column('venue_address', sa.String(length=400), nullable=False),
    sa.Column('maps_url', sa.String(length=600), nullable=False),
    sa.Column('dress_code', sa.Text(), nullable=False),
    sa.Column('gift_details', sa.Text(), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('flyer_url', sa.String(length=600), nullable=False),
    sa.Column('rsvp_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_trees',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('allocated_seats', sa.Integer(), nullable=False),
    sa.Column('max_extra_guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_trees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_trees_token'), ['token'], unique=True)

    op.create_table('rsvps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('invite_tree_id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.Column('rsvp_status', sa.String(length=20), nullable=False),
    sa.Column('seats_requested', sa.Integer(), nullable=False),
    sa.Column('note_to_celebrant', sa.Text(), nullable=True),
    sa.Column('dietary_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['invite_tree_id'], ['invite_trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rsvps_invite_tree_id'), ['invite_tree_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rsvps_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rsvps_phone'))
        batch_op.drop_index(batch_op.f('ix_rsvps_invite_tree_id'))

    op.drop_table('rsvps')
    with op.batch_alter_table('invite_trees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_trees_token'))

    op.drop_table('invite_trees')
    op.drop_table('events')
    op.drop_table('audit_logs')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
